---
framework: mocha
preMerge:
  pattern:
    - "./test/test-python-shell.js"
preRun:
     command:
        - npm ci
        - nom run compile
postMerge:
  pattern: 
    - "./test/test-python-shell.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml
nodeVersion: 12.22.6
version: 1.0
